version: '3'
services:
  busybox:
    image: busybox
    command: "ls /jfs"
    volumes:
      - jfsvolume:/jfs
volumes:
  jfsvolume:
    driver: jakubs22/juicefs:arm64-latest
    driver_opts:
      name: ${JFS_VOL}
      token: ${JFS_TOKEN}
      accesskey: ${JFS_ACCESSKEY}
      secretkey: ${JFS_SECRETKEY}
      subdir: ${JFS_SUBDIR}
